TagAttribute
apache/struts pull request #442
Opened 2020-10-15 05:22 UTC by lukaszlenart

WIP

2020-11-15 00:09 UTC, JCgH4164838Gh792C124B5 commented on core/src/main/java/org/apache/struts2/views/TagAttribute.java
> +    public TagAttribute escaped(){
Minor suggestion (spacing/readability):  change `(){`  to `() {`

2020-11-15 00:19 UTC, JCgH4164838Gh792C124B5 commented
Hello @lukaszlenart .

This looks like an interesting change.   😄  
I will try to review it in more detail when I have a chance.  It looks like the change might be introducing a failure (java.lang.ClassCastException) in the Showcase tests, as it stands right now (if I read the Travis CI reports correctly).

2021-02-06 22:10 UTC, JCgH4164838Gh792C124B5 requested changes
Hi @lukaszlenart .

I downloaded the branch for these changes, took another look, and attempted to build things locally.

Adding the additional methods suggested in the review and then modifying the components (either using the new conversion method, or relying on the implicit `toString()` addition) seemed to work for me locally.  This allowed the Showcase test that was failing to pass, and interactive tests for the Showcase UI components seemed to work OK.

I do not know if the changes suggested in this review are a good strategy or not, but I think in order to implement the `TagAttribute` there will need to be changes in places where the code assumes a component parameter will be a `TagAttribute` or `String` (so that it can handle either).

Depending on how many different types of `Component` parameter values might be encountered, some sort of general-purpose adapter might be a consideration (to convert from the various parameter types to `String` and back).  It does not look like it would be worth the overhead at the moment, though.

It looks like the idea for your PR works, with just a few boundary cases to deal with first.  Good work.  👍

2022-05-13 06:40 UTC, lukaszlenart commented
I'm closing this one - there are some tags that makes implementing this quite hard.

2022-05-13 06:40 UTC, closed without merging