Improved the StrutsUrlDecoder so that charset retrieval is performed only once.
apache/struts pull request #773
Opened 2023-10-23 14:01 UTC by mygreen

- StutsUrlDecoder has performance problems when run from multiple threads, because [Charset#availavleCharts(...)](https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/java.base/share/classes/java/nio/charset/Charset.java#L569-L588) called `StrutsUrlDecoder#getCharset(...)` is synchronized blocked.
  - Root causes is synchronized blocked at [AbstractCharsetProvider#charsets()](https://github.com/openjdk/jdk/blob/jdk-11%2B28/src/jdk.charsets/share/classes/sun/nio/cs/ext/AbstractCharsetProvider.java#L174-L177) .
- Therefore, `Charset#availavleCharts(...)` to be executed only once during class initialization.
- StutsUrlDecoder is used to evaluate custom tag [<s:url>](https://struts.apache.org/tag-developers/url-tag), it will have performance problems if it receives too many requests.

2023-10-23 14:07 UTC, sepe81 requested changes
LGTM otherwise

2023-10-23 14:07 UTC, sepe81 commented on core/src/main/java/org/apache/struts2/url/StrutsUrlDecoder.java
> +    private static final Collection<Charset> AVAILAVLE_CHARSETS = Charset.availableCharsets().values();
```suggestion
    private static final Collection<Charset> AVAILABLE_CHARSETS = Charset.availableCharsets().values();
```

2023-10-23 14:07 UTC, sepe81 commented on core/src/main/java/org/apache/struts2/url/StrutsUrlDecoder.java
> +        for (Charset charset : AVAILAVLE_CHARSETS) {
```suggestion
        for (Charset charset : AVAILABLE_CHARSETS) {
```

2023-10-24 13:50 UTC, lukaszlenart approved these changes
👏

2023-10-24 13:51 UTC, lukaszlenart commented
Would you mind opening a [JIRA](https://issues.apache.org/jira/projects/WW) ticket and link it here?

2023-10-25 10:07 UTC, mygreen commented
The fllowing JIRA tikcet was created.

https://issues.apache.org/jira/browse/WW-5359

2023-10-25 10:12 UTC, merged