[WW-5335] Prepares for Java 17 & Struts 7.x
apache/struts pull request #785
Opened 2023-11-12 10:16 UTC by lukaszlenart

Closes [WW-5335](https://issues.apache.org/jira/browse/WW-5335)

2023-11-12 10:29 UTC, kusalk requested changes

2023-11-12 10:29 UTC, kusalk commented on .github/workflows/codeql.yml
Need to add `java-version` to these job(s)

2023-11-12 10:29 UTC, kusalk commented on pom.xml
> +        <tag>release/struts-7-0-x</tag>
Convention here is usually `HEAD`

2023-11-12 10:39 UTC, lukaszlenart commented on .github/workflows/codeql.yml
like this?

2023-11-12 10:47 UTC, kusalk commented on .github/workflows/codeql.yml
I think so - let's see if the build goes green

2023-11-12 10:47 UTC, kusalk approved these changes

2023-11-13 21:43 UTC, sepe81 approved these changes
LGTM

2023-11-15 05:06 UTC, merged

2024-03-06 13:40 UTC, lukaszlenart commented
No exact plans but first 2.5.x must be EOL which will happen in two months so you can expect the first Struts 7.x around that date